language: ruby
rvm:
  - jruby-18mode
jdk:
  - oraclejdk7
before_install:
  - gem update --system
  - gem --version
install:
  bundle install
script:
  bundle exec buildr clean test:'-SimpleTest,-WasRun,-junit.tests.framework.*,-RuleChainTest,-TestWatchmanTest,-WithUnresolvedGenericTypeVariablesOnTheoryParms'
after_success:
  bundle exec buildr package test=no
